name: chintu

on:
  push:
    branches:
      - main

jobs:
  first-job-id:
    name: chintu
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: v1.10.5

      - name: Terraform init azurerm backend
        uses: ahmedig/terraform-azurerm-backend@v4
        with:
          resource_group_name: backend-rg
          storage_account_name: stgstate
          container_name: terraformstate
          # optionally specify a key (tfstate file name)
          key: prod.tfstate

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan


          
